### ISSUE TITLE
Feature request: Menu option to filter in both modes

### ISSUE THREAD

**Issue by marcustyphoon** [AprilSylph/Filtering-Plus#1]
### Concept

Tumblr differentiates between filtering post content and filtering tags, but realistically, if I want to filter posts related to a certain text string I usually don't care about the distinction and would like posts to be filtered regardless of whether the string is a tag or in the post body.

Thus, it would be awesome to have an additional menu option that added the string in question as both a filtered tag and a filtered phrase.

**Comment by AprilSylph** [comment]
I completely agree that content filtering not checking tags is bunk, but adding a "both" mode would mean that selected text would always have two options, which would make filtering post content just that tiny bit harder.

It would also be hard to communicate that adding a substring to both filtering lists would check the post content for that substring, but only check whole tags. The way it works currently means that filtering a tag will always filter the post being right-clicked, and I'd like to preserve that.

Ultimately the two filtering systems work completely differently, and giving the option to manipulate both at the same time I think will introduce more confusion than it's worth.
