### ISSUE TITLE
Userscript Version?

### ISSUE THREAD

**Issue by OrniiDiien** [AprilSylph/Filtering-Plus#5]
Hi, just curious if this would be possible, since I like to limit how many unique extensions I have installed and currently use Tampermonkey. Would it be possible for this extension to work as a userscript (considering it's written in 100% Javascript)?

**Comment by marcustyphoon** [comment]
Possibly, though I don't think `GM_registerMenuCommand` passes the userscript the currently selected text like the web extension API does; if that's true I imagine you would have to do some additional work with `window.getSelection()`.
